from django import forms

class TriviaForm(forms.Form):
    question_1 = forms.CharField(max_length=150)
    question_2 = forms.CharField(max_length=150)
    question_3 = forms.CharField(max_length=150)
    question_4 = forms.CharField(max_length=150)
    question_5 = forms.CharField(max_length=150)
    question_6 = forms.CharField(max_length=150)
    question_7 = forms.CharField(max_length=150)
    question_8 = forms.CharField(max_length=150)
    question_9 = forms.CharField(max_length=150)
    question_10 = forms.CharField(max_length=150)
    question_11 = forms.CharField(max_length=150)
    question_12 = forms.CharField(max_length=150)
    question_13 = forms.CharField(max_length=150)
    question_14 = forms.CharField(max_length=150)
    question_15 = forms.CharField(max_length=150)
    question_16 = forms.CharField(max_length=150)
    question_17 = forms.CharField(max_length=150)
    question_18 = forms.CharField(max_length=150)
    question_19 = forms.CharField(max_length=150)
    question_20 = forms.CharField(max_length=150)